app:
  name: "GraduationWork_model"
  env: "dev"
  log_level: "INFO"

paths:
  base_dir: "."
  input_dir: "./data/input"
  output_dir: "./data/output"
  log_dir: "./data/logs"

database:
  host: "localhost"
  port: 3306
  user: "gw"
  password: "569332"          # 开发环境建议使用本地低权限账号
  db: "graduation_work"
  url: "jdbc:mysql://localhost:3306/graduation_work"
  driver-class-name: "com.mysql.cj.jdbc.Driver"

